# Generated by Django 3.1.2 on 2020-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='created',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
