# Generated by Django 3.1.2 on 2020-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201114_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
