# Generated by Django 3.1.2 on 2020-11-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201116_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='receive_by',
            new_name='recieve_by',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='receive_quantity',
            new_name='recieve_quantity',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='receive_by',
            new_name='recieve_by',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='receive_quantity',
            new_name='recieve_quantity',
        ),
    ]
